### ISSUE TITLE
chime_tts.say plays wrong/older messages

### ISSUE THREAD

**Issue by s-gordon** [nimroddolev/chime_tts#71]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Calling `chime_tts.say` with tts.piper seems to pick older audio files at random for the media_player. Independent of cache being enabled or disabled. I use Hello world in the example below, but as the message changes it seems to grab historical mp3 at random.

```yaml
service: chime_tts.say
target:
  entity_id: media_player.living_room
data:
  chime_path: bright
  end_chime_path: bright
  delay: 450
  final_delay: 0
  tts_playback_speed: 100
  volume_level: 0.2
  message: Hello world
  tts_platform: tts.piper
  announce: true
```

### Describe the solution you'd like

The specified message to be played.

### Describe alternatives you've considered

I have tried clearing cache; no luck there.

### Additional context

N/A

**Comment by dbullendsl** [comment]
I haven't seen anything like this in my system

**Comment by s-gordon** [comment]
> repeated calls to Chime TTS with the exact same parameters that result in either cached audio or newly generated audio, at random:

Both, actually. Calling using the same parameters (including the message string) led to an older, presumably cached, audio being played. Occasionally this would also use newly generated audio for a new message string, but this was difficult to reliably reproduce.

It's frustrating, but in the course of enabling debugging (and restarting HA) the issue seems to have disappeared. Early days yet, but fingers crossed that it lasts.

Thanks.

**Comment by nimroddolev** [comment]
I see. Enabling debugging shouldn't result in any functional changes, but restarting Home Assistant may have helped...it's all very unclear.

To address the issue I will need to review your debug logs after it occurs. To do so I would like to ask you to please :
1. Clear your Chime TTS cache by calling service: `chime_tts.clear_cache`
2. Clear your Home Assistant TTS cache by calling service: `tts.clear_cache`
3. Enable debug logging for Chime TTS
```
service: logger.set_level
data:
  custom_components.chime_tts: debug
```
If/when the issue reoccurs please navigate to your logs and isolate the debug logs for that service call.
⚠️ If you restart home assistant **_you will need to re-enable debug logging_** (see step 3 above).

Thank you.

**Comment by uli-rpi** [comment]
I have been observing the problem for a long time, so it already existed for me before the last update. 
I can confirm @s-gordon's statement, either older, previously unplayed messages are played, or none at all. 

After the last update, practically no more messages are played, unless HA was restarted shortly before.

**Comment by nimroddolev** [comment]
Hi @uli-rpi, I am sorry you're also experiencing the issue.

In order to resolve the issue I will need more information. Could you please provide me with answers to the following?
1. Do you recall when the issues started? Either the Chime TTS version number, or roughly how long ago / how many releases ago?
2. Can you please clear your Chime TTS cache (by calling service: `chime_tts.clear_cache`) and your Home Assistant TTS cache (by calling service: `tts.clear_cache`) and report back if the issue still occurs?
3. With debug logging enabled, can you please try to trigger the issue, and provide the associated log data?

To enable debug logging:
```
service: logger.set_level
data:
  custom_components.chime_tts: debug
```

**Comment by uli-rpi** [comment]
Hello @nimroddolev, 
- I use Chime TTS since Version 0.10.2, and have been monitoring the problem since then
- The chime cache is cleared before each call of CTTS 
- I have to test clearing the tts cahce additionally

[home-assistant_2024-01-10T14-01-32.043Z.log](https://github.com/nimroddolev/chime_tts/files/13888767/home-assistant_2024-01-10T14-01-32.043Z.log)

**Comment by nimroddolev** [comment]
Thanks @uli-rpi but unfortunately the logs you sent do not include the debug log messages.
Can you please first enable the debug logs? The steps to do so are included in my previous messages

**Comment by uli-rpi** [comment]
I mean that the output is always 3 - 4 steps behind. 
This time the tts cache was also cleared before each output.

[home-assistant_2024-01-10T14-23-44.697Z.log](https://github.com/nimroddolev/chime_tts/files/13888923/home-assistant_2024-01-10T14-23-44.697Z.log)

**Comment by nimroddolev** [comment]
Thank you for the log messages. I was able to see where the integration crashes in your log messages and have just released a new beta version with a fix.

I would like to ask both of you @uli-rpi  and @s-gordon to please upgrade Chime TTS to the new beta, v0.11.2-beta1 and report back if the issue is now resolved.

To install the new beta version:
1. Open the <a href="https://my.home-assistant.io/redirect/hacs_repository/?owner=nimroddolev&repository=chime_tts&category=integration" title="Chime TTS HACS repository" target="_blank">Chime TTS repository in HACS</a>
1. Click on the `⋮` button in the top right
1. Select the `↻ Redownload` option
1. Enable the `Show beta versions` option
1. Select version `v0.11.2-beta1` from the updated version drop-down list

**Comment by uli-rpi** [comment]
Result of the first short test, the error no longer occurs.

**Comment by nimroddolev** [comment]
Excellent. Can you please update once you've had a chance to do more in depth testing?

**Comment by uli-rpi** [comment]
@nimroddolev, I have tested the beta under various conditions, from my side the issue is resolved.

**Comment by nimroddolev** [comment]
Thank you @uli-rpi.
@s-gordon can you please report whether the new beta resolved the issue for you as well?

**Comment by s-gordon** [comment]
@nimroddolev 

Thanks for rolling out a hotfix for this. I'm away from home for a few days, but will test this and report back once I return.

**Comment by def1149** [comment]
I had this problem too. the Beta fixed it. Thanks

**Comment by DanDixon** [comment]
I just switched to v0.12.1-beta1, but I'm still having this problem.

I updated to the beta without clearing the cache and it seemed to work after Home Assistant restarted, but later it messed up again.

After running both of these:
chime_tts.clear_cache
tts.clear_cache
... It seems to be working again.

I'll report again if the problem reemerges.

**Comment by nimroddolev** [comment]
Hi @DanDixon. I’m sorry to hear you’re still experiencing the issue.

In order to better understand what might be causing the issue I will need more information. Can you to please provide debug logs for when the issue occurs?

**Comment by DanDixon** [comment]
Here's a partial log file filtered by chime_tts
Let me know what else I can provide to help.

[home-assistant_2024-01-17-chime-tts-dan-dixon.txt](https://github.com/nimroddolev/chime_tts/files/13972064/home-assistant_2024-01-17-chime-tts-dan-dixon.txt)

**Comment by uli-rpi** [comment]
Hello @nimroddolev, the error has occurred again, i am currently using beta v0.11.2beta1. 

First there is no output, then the content that was not previously played is played in the next output or the one after that. Unfortunately, I cannot specifically reproduce the error. After a restart of HA it works again.

![IMG_8786](https://github.com/nimroddolev/chime_tts/assets/84666727/57ca3a1c-027f-47cb-af3c-ebfce44790dc)

**Comment by nimroddolev** [comment]
Thanks for the additional info. I think I will need to refactor the queue functionality. I will update once I have a working beta that you can test.

**Comment by frejdej** [comment]
I have same problem. Temporary solve this with chime integration reload before every TTS message:
```
service: homeassistant.reload_config_entry
data:
  entry_id: f8e1b74bb791a2a9573b7e159d2fb726
```

**Comment by nimroddolev** [comment]
I have released a new beta version, v0.12.1-beta5, where I have refactored the queue code. Can you please upgrade and let me know if the issue still persists?

To install the new beta version:
1. Open the <a href="https://my.home-assistant.io/redirect/hacs_repository/?owner=nimroddolev&repository=chime_tts&category=integration" title="Chime TTS HACS repository" target="_blank">Chime TTS repository in HACS</a>
1. Click on the `⋮` button in the top right
1. Select the `↻ Redownload` option
1. Enable the `Show beta versions` option (it may take a moment to update the list)
1. Select version `v0.12.1-beta5` from the updated version drop-down list
1. Restart Home Assistant

**Comment by def1149** [comment]
I updated and sent multiple different messages with no problems.
```service: chime_tts.say
target:
  device_id: 5ee58c347fd86dda99e9d12179b1cd7e
data:
  delay: 450
  tts_playback_speed: 100
  volume_level: 1
  chime_path: bells
  message: This is a test after change two
  tts_platform: tts.piper
  announce: false
  cache: true
```

**Comment by dimatx** [comment]
I have this issue as well with beta4, going to try beta5 to see if it resolves it. It sometimes worked for several days before playing older messages, so might take some time to know if beta5 truly addresses the issue.

**Comment by nimroddolev** [comment]
> I have this issue as well with beta

The fix is only from beta4

> might take some time to know if beta5 truly addresses the issue.

Understood. Please update when you can. 🙏

**Comment by uli-rpi** [comment]
I'm also testing beta 5 :-)

**Comment by nimroddolev** [comment]
I’m happy to hear the queue issue seems to be resolved!

If you experience the second issue again (the one which required a restart of HA) please let me know. For now there’s not really enough for me to go on.

**Comment by nimroddolev** [comment]
I released version v0.13.0 which includes the queue fix. Thank you for helping with testing 👍

**Comment by dimatx** [comment]
Haven't had issues since beta 5 :)
